// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsDjVybwMawuskEco13NDoTDRB0Ml2L1w',
    appId: '1:167858604740:web:e8924510cfabdea4375791',
    messagingSenderId: '167858604740',
    projectId: 'elderease-41524',
    authDomain: 'elderease-41524.firebaseapp.com',
    databaseURL: 'https://elderease-41524-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderease-41524.appspot.com',
    measurementId: 'G-2B6E6B110G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkzGOGIQ3ROiTvoIYAr6f5yd5phcCz__M',
    appId: '1:167858604740:android:50d4228504135a59375791',
    messagingSenderId: '167858604740',
    projectId: 'elderease-41524',
    databaseURL: 'https://elderease-41524-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderease-41524.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCma9NZ4vJf-HatFtcJkf9vTmKQ7cwxSRU',
    appId: '1:167858604740:ios:1846e0753f1a4540375791',
    messagingSenderId: '167858604740',
    projectId: 'elderease-41524',
    databaseURL: 'https://elderease-41524-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderease-41524.appspot.com',
    iosBundleId: 'com.example.evesguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCma9NZ4vJf-HatFtcJkf9vTmKQ7cwxSRU',
    appId: '1:167858604740:ios:1846e0753f1a4540375791',
    messagingSenderId: '167858604740',
    projectId: 'elderease-41524',
    databaseURL: 'https://elderease-41524-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderease-41524.appspot.com',
    iosBundleId: 'com.example.evesguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsDjVybwMawuskEco13NDoTDRB0Ml2L1w',
    appId: '1:167858604740:web:57fc58db679f087f375791',
    messagingSenderId: '167858604740',
    projectId: 'elderease-41524',
    authDomain: 'elderease-41524.firebaseapp.com',
    databaseURL: 'https://elderease-41524-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderease-41524.appspot.com',
    measurementId: 'G-YEWESMZL6B',
  );

}